export const HttpMessage = {
   SERVER_ERROR: "INTERNAL SERVER ERROR",
   NOT_FOUND: "REQUEST NOT FOUND",
   BAD_REQUEST: "BAD REQUEST",
   SUCCESS: "REQUEST SUCCESS",
   CREATED: "REQUEST CREATED",
   UPDATED: "REQUEST UPDATED",
   DELETED: "REQUEST DELETED",
   USER_EXIST: "EMAIL ALREADY USED",
   INVALID_CREDENTIAL: "INVALID CREDENTIAL"
}